[package]
name = "rlp_derive"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[lib]
name = "rlp_derive"
proc-macro = true

[dependencies]
syn = "0.13"
quote = "0.5"

[dev-dependencies]
rlp = { git = "https://github.com/c0gent/parity-common", branch = "ring-0.13" }
