[package]
name = "rlp_compress"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rlp = { git = "https://github.com/c0gent/parity-common", branch = "ring-0.13" }
elastic-array = "0.10"
lazy_static = "1.0"
